modules: Re-order RenderingOpenGL libraries to fix VTK_ENABLE_KIT link error
This commit fixes the the order of libraries associated with
the vtkRenderingOpenGL module to ensure the associated kit (introduced
by 094a09a) can be linked successfully on Linux.

More specifically, in case the NVCtrl static library is found, it is
important to make sure it is added first in the list. That way, when
the kits are linked to their associated public and private libraries (see
target_link_libraries in vtkModuleTop.cmake), the eventual duplicate
libraries removed from the list of public or private libraries are always
listed after the static library and we are sure no symbol will be skipped.

The link error fixed by this commit is the following:

//-------------
Linking CXX shared library lib/libvtkOpenGL-6.2.so
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `close_display':
(.text+0x22): undefined reference to `XextRemoveDisplay'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `find_display':
(.text+0x41): undefined reference to `XextCreateExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `find_display':
(.text+0x71): undefined reference to `XextFindDisplay'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `find_display':
(.text+0xaa): undefined reference to `XextAddDisplay'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `XNVCTRLQueryVersion':
(.text+0x2a9): undefined reference to `XMissingExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `XNVCTRLIsNvScreen':
(.text+0x462): undefined reference to `XMissingExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `XNVCTRLQueryTargetCount':
(.text+0x605): undefined reference to `XMissingExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `XNVCTRLSetTargetAttribute':
(.text+0x7a2): undefined reference to `XMissingExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o): In function `XNVCTRLSetTargetAttributeAndGetStatus':
(.text+0x99d): undefined reference to `XMissingExtension'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libXNVCtrl.a(NVCtrl.o):(.text+0xbb6): more undefined references to `XMissingExtension' follow
collect2: error: ld returned 1 exit status
make[3]: *** [lib/libvtkOpenGL-6.2.so.1] Error 1
make[2]: *** [CMakeFiles/vtkOpenGL.dir/all] Error 2
make[1]: *** [CMakeFiles/vtkOpenGL.dir/rule] Error 2
make: *** [vtkOpenGL] Error 2
//-------------

Change-Id: I0288c598f183a9537d0dded97af9323754fdea2a