[regression] COMP: vtkQWidgetTexture: Fix undefined _glPixelStorei symbol link error on macOS
This commit fixes link error introduced in 037b1f7950f5b ([backport] add
qwidgets in a vtk rendering with events)

Thanks @pieper for reporting the issue.

  [ 50%] Linking CXX shared library ../../lib/libvtkGUISupportQt-8.2.dylib
  Undefined symbols for architecture x86_64:
    "_glPixelStorei", referenced from:
        vtkQWidgetTexture::vtkQWidgetTexture()::$_0::operator()() const in vtkQWidgetTexture.cxx.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[5]: *** [lib/libvtkGUISupportQt-8.2.1.dylib] Error 1
  make[4]: *** [GUISupport/Qt/CMakeFiles/vtkGUISupportQt.dir/all] Error 2
  make[4]: *** Waiting for unfinished jobs....